"""Update countries population defualt table 1

Revision ID: 3a05cc1e4230
Revises: 3798bf19a58a
Create Date: 2025-12-11 12:42:03.858355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a05cc1e4230"
down_revision: Union[str, Sequence[str], None] = "3798bf19a58a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("population", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countries", "population")
    # ### end Alembic commands ###
