"""country migration

Revision ID: 47a1f151cb8f
Revises: e0fd07a9f797
Create Date: 2025-12-11 12:13:15.506510

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "47a1f151cb8f"
down_revision: Union[str, Sequence[str], None] = "e0fd07a9f797"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
