"""Update countries table

Revision ID: 54019045b351
Revises: 724a69ef3423
Create Date: 2025-12-11 12:38:07.156180

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "54019045b351"
down_revision: Union[str, Sequence[str], None] = "724a69ef3423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
