"""Update countries population defualt table

Revision ID: 60f735becb5b
Revises: 86fa405794f1
Create Date: 2025-12-11 12:39:52.115329

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "60f735becb5b"
down_revision: Union[str, Sequence[str], None] = "86fa405794f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
