"""Update countries table

Revision ID: 724a69ef3423
Revises: 9acb70c0b8ab
Create Date: 2025-12-11 12:29:45.541935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "724a69ef3423"
down_revision: Union[str, Sequence[str], None] = "9acb70c0b8ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("calling_codes", sa.JSON(), nullable=True))
    op.drop_column("countries", "native_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries",
        sa.Column(
            "native_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("countries", "calling_codes")
    # ### end Alembic commands ###
