"""Update countries population defualt table

Revision ID: 86fa405794f1
Revises: 54019045b351
Create Date: 2025-12-11 12:39:18.323661

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "86fa405794f1"
down_revision: Union[str, Sequence[str], None] = "54019045b351"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
