"""Create countries table

Revision ID: 9acb70c0b8ab
Revises: 47a1f151cb8f
Create Date: 2025-12-11 12:22:29.396559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9acb70c0b8ab"
down_revision: Union[str, Sequence[str], None] = "47a1f151cb8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("native_name", sa.String(length=255), nullable=True),
        sa.Column("alpha2_code", sa.String(length=2), nullable=True),
        sa.Column("alpha3_code", sa.String(length=3), nullable=True),
        sa.Column("capital", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("subregion", sa.String(length=100), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("timezones", sa.JSON(), nullable=True),
        sa.Column("borders", sa.JSON(), nullable=True),
        sa.Column("currencies", sa.JSON(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("flag_svg", sa.String(length=500), nullable=True),
        sa.Column("flag_png", sa.String(length=500), nullable=True),
        sa.Column("independent", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_countries_alpha2_code"), "countries", ["alpha2_code"], unique=True
    )
    op.create_index(
        op.f("ix_countries_alpha3_code"), "countries", ["alpha3_code"], unique=True
    )
    op.create_index(
        op.f("ix_countries_latitude"), "countries", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_countries_longitude"), "countries", ["longitude"], unique=False
    )
    op.create_index(op.f("ix_countries_name"), "countries", ["name"], unique=False)
    op.create_index(op.f("ix_countries_region"), "countries", ["region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_region"), table_name="countries")
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.drop_index(op.f("ix_countries_longitude"), table_name="countries")
    op.drop_index(op.f("ix_countries_latitude"), table_name="countries")
    op.drop_index(op.f("ix_countries_alpha3_code"), table_name="countries")
    op.drop_index(op.f("ix_countries_alpha2_code"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
